### ISSUE TITLE
VM.h:7:10: fatal error: opcodes.h: No such file or directory

### ISSUE THREAD

**Issue by bsperryn** [fraca7/dsremap#3]
Hello, 

I have a 3.3v Arduino Pro Micro (Leonardo in miniture) I've set up LUFA and I've put your arduiino/dsremap directory into Libraries.

I'm trying to compile the contents of dsremap.ino and I'm getting the following error:

VM.h:7:10: fatal error: opcodes.h: No such file or directory

I can't seem to find this file anywhere, which library is this part of?

Thank you!
Brian

**Comment by bsperryn** [comment]
I'm now trying to "python ./make.py firmware" but running into problems, will keep at it.

**Comment by fraca7** [comment]
You don't need to copy anything in Libraries (except for LUFA), the code should build in-place. opcodes.h is generated by make.py indeed; what problem do you have running it exactly ?

**Comment by bsperryn** [comment]
I'm running OSX Catalina 10.15.7.

At first I was having a problem because I was using Python2. Then I started using Python 3 and started getting a different error related to not having PyQt5.

Now I've installed PyQt5 and I'm getting the following error: 

```
python3 ./make.py firmware
Traceback (most recent call last):
  File "./make.py", line 13, in <module>
    from dsrlib.meta import Meta
  File "./src/dsrlib/meta.py", line 12, in <module>
    from PyQt5 import QtCore, QtGui
ImportError: dlopen(/usr/local/lib/python3.9/site-packages/PyQt5/sip.so, 2): Symbol not found: _PyCMethod_New
  Referenced from: /usr/local/lib/python3.9/site-packages/PyQt5/sip.so
  Expected in: flat namespace
 in /usr/local/lib/python3.9/site-packages/PyQt5/sip.so
```

Unfortunately I'm not finding much about this online...

**Comment by bsperryn** [comment]
I've tried to run `python3 ./make.py headers` and I get the same error.

Would it be possible to send me the log and opcode constant files? Is this all I will need to build it using the Arduino IDE?
